
# Site settings
title: HLC fans
description: _description_
owner:
  name: _your name_ # or company name
  url: "http://example.com" # your URL
first_published: 2010 # if migrating another site, the year of your first publish
                      # Must be a 4-digit integer year (math is used on it)
# url: "http://example.com" # the base hostname & protocol for this site
baseurl: "" # the subpath of your site, e.g. /blog
            # Note you'll have to move your robots.txt to the root if you want it used.
            # And list multiple sitemaps if there are other subdirectories you want indexed
            # besides this blog.
lang: en-us # used in HTML lang attributes

# on landing page
# - set the introduce copy
introTitle: HLC fans
introDetail: HLC fans is a global open source community, focusing on <br/>blockchain technology exchange and promotion,<br/>especially block-DAG technology in HLC.


# - title for your menus parts

menu:
  - title : DOCS
    href: ''
  - title : Blog
    href: ''
  - title : News
    href: ''
  - title : Community
    href: ''


# # on all pages (and the first three you list display with greeting, if included)
# social:
twitter: https://twitter.com/halalchain
github: https://github.com/hlcfans/hlcfans.github.io/
facebook-official: https://www.facebook.com/halalchain
#   linkedin-square: https://linkedin.com/in/_username_
#   google-plus-square: https://plus.google.com/u/0/+_username_
#   email: /contact/ # you can configure and use this contact page or use your email addy

 


# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# Github pages posts future posts by default.
# You'll want to move the user guide posts to _drafts if you set this to true.
future: false

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']


# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []


